##
## Makefile for ok in /home/abdel/lem-in
## 
## Made by abdel cherkaoui
## Login   <abdel@epitech.net>
## 
## Started on  Wed Apr 12 14:24:02 2017 abdel cherkaoui
## Last update Sun May 14 20:50:23 2017 abdel cherkaoui
##

CC	:= gcc

RM	:= rm -rf

SRCS	:= ./my_monster.c

NAME	:= solver

all:
	$(CC) $(SRCS) -O2 -O3 -O -Os -o $(NAME)

clean:
	$(RM) $(NAME)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all re clean fclean
